name: Run Email Action

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f2001506@ds.study.iitm.ac.in
        run: echo "Hello from GitHub Actions!"
